FROM rust:latest AS builder
RUN git clone https://github.com/iden3/circom.git
WORKDIR /circom
RUN cargo build --release
RUN cargo install --path circom

FROM node:latest
COPY --from=builder /usr/local/cargo/bin/circom /usr/local/bin/circom
WORKDIR /app
RUN npm init
RUN npm install circomlib
RUN npm install -g snarkjs

COPY ./contracts/poseidon_hasher.circom /app/poseidon_hasher.circom
COPY ./generate_ptau.sh /app/generate_ptau.sh


CMD ["./generate_ptau.sh"]
# CMD ["/bin/bash"]
